MONGODB_HOST: mongodb-{{ environment }}.pavithra.sbs
CATALOGUE_HOST: catalogue-{{ environment }}.pavithra.sbs
CART_HOST: cart-{{ environment }}.pavithra.sbs
MYSQL_HOST: mysql-{{ environment }}.pavithra.sbs
PAYMENT_HOST: payment-{{ environment }}.pavithra.sbs
RABBITMQ_HOST: rabbitmq-{{ environment }}.pavithra.sbs
REDIS_HOST: redis-{{ environment }}.pavithra.sbs
SHIPPING_HOST: shipping-{{ environment }}.pavithra.sbs
USER_HOST: user-{{ environment }}.pavithra.sbs