MONGODB_HOST: mongodb-{{ env }}.pavithra.sbs
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.pavithra.sbs
CART_HOST: cart.backend-alb-{{ env }}.pavithra.sbs
MYSQL_HOST: mysql-{{ env }}.pavithra.sbs
PAYMENT_HOST: payment.backend-alb-{{ env }}.pavithra.sbs
RABBITMQ_HOST: rabbitmq-{{ env }}.pavithra.sbs
REDIS_HOST: redis-{{ env }}.pavithra.sbs
SHIPPING_HOST: shipping.backend-alb-{{ env }}.pavithra.sbs
USER_HOST: user.backen-alb-{{ env }}.pavithra.sbs