[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[mongodb]
mongodb.pavithra.sbs

[catalogue]
catalogue.pavithra.sbs

[mysql]
mysql.pavithra.sbs

[rabbitmq]
rabbitmq.pavithra.sbs

[redis]
redis.pavithra.sbs

[cart]
cart.pavithra.sbs

[user]
user.pavithra.sbs

[frontend]
pavithra.sbs

[payment]
payment.pavithra.sbs

[shipping]
shipping.pavithra.sbs

