  - name: app setup
    ansible.builtin.import_role:
     name: common
     tasks_from: app-setup.yaml

  - name: installing nodejs
    ansible.builtin.import_role:
     name: common
     tasks_from: install-nodejs.yaml

  - name: copying {{ component }} service file
    ansible.builtin.import_role:
     name: common
     tasks_from: system-setup.yaml