- name: disabling default nodejs
  ansible.builtin.command:
    dnf module disable nodejs -y 

- name: enabling nodejs 20
  ansible.builtin.command:
    dnf module enable nodejs:20 -y 

- name: installing nodejs
  ansible.builtin.command:
    dnf install nodejs -y 

- name: installing dependencies
  community.general.npm:
    path: /app